name: Build

on: [push]

jobs:
  build:
    name: Build [${{ matrix.os }}][${{ matrix.node }}]

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [
          '10.x',
          '12.x',
          '14.x',
          '15.x',
        ]
        os: [
          macOS-latest,
          ubuntu-latest,
          windows-latest,
        ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install

      - name: Format
        run: yarn prettier

      - name: Build
        run: yarn build
